### ISSUE TITLE
InstalledAppFlow.run_local_server() asserts self.redirect_uri ends with '/'

### ISSUE THREAD

**Issue by glasvase** [googleapis/google-auth-library-python-oauthlib#110]
#### Environment details

  - OS type and version: macOS 11.2
  - Python version:  3.9.1
  - pip version: 21.0.1
  - `google-auth-oauthlib` version: 0.4.3

The line below sets `InstalledAppFlow.redirect_uri` always ends with `/`, which seems to be undesirable for users who tend to assign `http://localhost:8080` to their app's url as [Google's docs](https://developers.google.com/identity/protocols/oauth2/web-server#creatingcred) suggest.
https://github.com/googleapis/google-auth-library-python-oauthlib/blob/59e4c5865976b0123e67016330dc3768c1774011/google_auth_oauthlib/flow.py#L461

This issue has already been raised 2 years ago in [stackoverflow](https://stackoverflow.com/questions/55142909/installedappflow-run-local-server-systematically-add-a-slash-to-the-end-of-t), which I found after struggling with `Error 400: redirect_uri_mismatch` and after being entangled with all the ill-formed documents and deprecated solutions.
I do not insist that the line should be deemed a bug, as I'm not expert on network things. But I hope some kind of retouch is applied so that users who rely on Google's guides and docs don't have to experience an otherwise avoidable error and frustration.

Thanks!

**Comment by busunkim96** [comment]
@arithmetic1728 I think this has come up a few times in this repo. Can the OAuth2 docs be updated to have the trailing slash (maybe just for Python samples?)

**Comment by arithmetic1728** [comment]
@busunkim96 I think maybe I can provide user a `redirect_uri_trailing_slash` kw argument in `run_local_server` method. The default value is `False` so it doesn't break existing users. For new users, if their `redirect_uri` in pantheon doesn't have trailing slash, they can pass `True` to not to use trailing slash.

**Comment by arithmetic1728** [comment]
@glasvase Fixed this in release 0.4.4. Please pass `redirect_uri_trailing_slash=False` to `run_local_server` to remove the trailing slash.
