### ISSUE TITLE
How to get email from credentials

### ISSUE THREAD

**Issue by myunghoon-chung** [googleapis/google-auth-library-python-oauthlib#131]
Hello. After executing the code as shown below, I tried to check the email with the corresponding credentials.
However, it failed to check the email information, and even the case of google was opened.
But support tells me again to contact git.
Can you check that part?

appflow = flow.InstalledAppFlow.from_client_secrets_file(
            "client_secret.json",
            scopes=["https://www.googleapis.com/auth/bigquery", "https://www.googleapis.com/auth/devstorage.full_control"],
            # redirect_uri='urn:ietf:wg:oauth:2.0:oob'
        )
        # auth_uri = appflow.authorization_url()
        if self.launch_browser:
            appflow.run_local_server()
        else:
            appflow.run_console()

        self.credentials = appflow.credentials

As shown below, the general credential seems to contain email information, but the credential issued by the code above does not contain email information.
$ curl "https://www.googleapis.com/oauth2/v1/tokeninfo?access_token=$(gcloud auth print-access-token)"
{
  ...
  "scope": "......",
  "expires_in": 3598,
  "email": "MY_EMAIL@email.com",
  "verified_email": true,
  "access_type": "offline"
}

**Comment by westarle** [comment]
Closing due to age.  Please reopen if you still have this issue.
