### ISSUE TITLE
ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by brentvollebregt** [googleapis/google-auth-library-python-oauthlib#145]
`google-auth` 2.0.0 was released a few hours ago which `google-auth-oauthlib` depends on. The latest version 2.0.0 is now being used because the dependency `google-auth>=1.0.0` is specified.

It appears `google-auth` 2.0.0 drops support for Python 2.7 and with this [dropped the dependency of `six`](https://github.com/googleapis/google-auth-library-python/compare/v1.35.0...v2.0.0#diff-468b4eb6967541466e04c6e35512e925b998fb4a8b489713ea098b107cd643b6) which exists in 1.35.0 (latest compatible). This library (`google-auth-oauthlib`) requires `six` but does not declare it as a dependency - it was relying on a dependency having it as a dependency.

`six` needs to be added as a dependency to fix this.

#### Environment details

  - OS type and version: Windows (originally discovered on ubuntu-18.04)
  - Python version: 3.7
  - pip version: 19.2.3
  - `google-auth-oauthlib` version: 0.4.5

#### Steps to reproduce

  1. Create a new Python virtual environment
  2. Activate the virtual environment
  3. Install google-auth-oauthlib: `pip install google-auth-oauthlib`
  4. Execute the code example below

A positive result will not throw any exceptions in step 4 whereas it now does.

To prove it worked previously, extending the steps above:
 1. Install the old `google-auth` library: `pip install google-auth==1.35.0`
 2. Execute the code example below

#### Code example

```python
from google_auth_oauthlib.flow import InstalledAppFlow
```

> Based on the example import from [here](https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.flow.html?highlight=InstalledAppFlow#google_auth_oauthlib.flow.InstalledAppFlow).

#### Stack trace
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from google_auth_oauthlib.flow import InstalledAppFlow
  File "C:\Users\Brent\GitHub\my-actions\.venv\lib\site-packages\google_auth_oauthlib\__init__.py", line 21, in <module>
    from .interactive import get_user_credentials
  File "C:\Users\Brent\GitHub\my-actions\.venv\lib\site-packages\google_auth_oauthlib\interactive.py", line 24, in <module>
    import google_auth_oauthlib.flow
  File "C:\Users\Brent\GitHub\my-actions\.venv\lib\site-packages\google_auth_oauthlib\flow.py", line 70, in <module>
    from six.moves import input
ModuleNotFoundError: No module named 'six'
```

**Comment by busunkim96** [comment]
Thank you for the report! I believe we can remove the usage of `six` in this library. I've opened #146.
