### ISSUE TITLE
No way to specify the audience id

### ISSUE THREAD

**Issue by rseymour** [googleapis/google-auth-library-python-oauthlib#238]
Using your tool to connect to your service it will return an id token with the audience set to the client_id.  As far as I can tell there's no way in this code to set that correctly.  With OOB copy/paste flow going out of style, you gave us a tool that almost works. But in the end feels like this: 
<img width="608" alt="image" src="https://user-images.githubusercontent.com/105805/193087218-efbc4255-96f1-4882-b31e-963da4d32d2d.png">

**Comment by keriwarr** [comment]
#300

**Comment by westarle** [comment]
Please reopen if this wasn't fixed in #300
