### ISSUE TITLE
run_local_server blocks if port is unavailable

### ISSUE THREAD

**Issue by wrouesnel** [googleapis/google-auth-library-python-oauthlib#28]
Executing
```
flow.run_local_server(host='localhost',
    port=8888, 
    authorization_prompt_message='Please visit this URL: {url}', 
    success_message='The auth flow is complete; you may close this window.',
    open_browser=True)
```
with something listening on port 8888 already blocks the process, rather then returning an error message.

Would be partially mitigated by #23 being merged, but this situation should throw an exception.

**Comment by busunkim96** [comment]
@wrouesnel Would you know of a good way to check if a host/port combination is available?

With #33 being merged, we could also potentially set the default port to `0` rather than `8080` to reduce the likelihood of this happening.

**Comment by busunkim96** [comment]
I suspect this only happens in some specific situations? If you are able to provide more details, that would be very much appreciated @wrouesnel.

I was not able to replicate this by starting a server on 8080 and then running the flow on 8080.

1. Start a simple server at localhost:8080. 
`python3 -m http.server localhost:8080`
2. Run the flow.
```
flow.run_local_server(host='localhost',
    port=8080, 
    authorization_prompt_message='Please visit this URL: {url}', 
    success_message='The auth flow is complete; you may close this window.',
    open_browser=True)
```

3. Get an error about port already being used:
```
Traceback (most recent call last):
  File "sheets.py", line 55, in <module>
    main()
  File "sheets.py", line 33, in main
    creds = flow.run_local_server(host='localhost', port=8080)
  File "/usr/local/google/home/busunkim/misc/fixit/sheets-sample/env/lib/python3.6/site-packages/google_auth_oauthlib/flow.py", line 425, in run_local_server
    host, port, wsgi_app, handler_class=_WSGIRequestHandler)
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 153, in make_server
    server = server_class((host, port), handler_class)
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```
---


If there are no responses to this issue by **September 30, 2019**, please close the issue.

**Comment by busunkim96** [comment]
Closing as there has been no response. 

Please open a **new** issue if you are experiencing this issue. Thanks!
