### ISSUE TITLE
Mismatch in credentials.json keys and that expected by this library.

### ISSUE THREAD

**Issue by break-through** [googleapis/google-auth-library-python-oauthlib#306]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/google-auth-library-python-oauthlib/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version: WSL running Windows 11 (I think WSL 2)
  - Python version: `python --version` - python 3.7 as a virtual environment
  - pip version: `pip --version` pip - pip 22.0.4
  - `google-auth-oauthlib` version: `pip show google-auth-oauthlib` - shows 1.0.0 ; but the code in this repo also doesn't parse the Google Cloud credentials.json afaik.

#### Steps to reproduce

  1. Download the credentials.json from the Cloud Console (API) under a desktop app (since running python on shell)
  2. Run code that uses it - specifically uses https://google-auth-oauthlib.readthedocs.io/en/latest/_modules/google_auth_oauthlib/flow.html#InstalledAppFlow. 
  3. Keep failing on authorizing to generate token.json.
  4. Realize that the library parses 'installed' and 'web', but the credentials.json contains none of those keys.
  5. Note this is a sudden thing; it was working fine the last time I had to refresh, about a week back.

#### Code example

```python
flow = InstalledAppFlow.from_client_secrets_file(
                'credentials.json', SCOPES)
creds = flow.run_console() # I just want the URL to authorize myself
```

#### Stack trace
```
PyEnv/lib/python3.7/site-packages/google_auth_oauthlib/flow.py", line 159, in from_client_config                                                          
raise ValueError("Client secrets must be for a web or installed app.")
ValueError: Client secrets must be for a web or installed app. 
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by clundin25** [comment]
The oauth JSON config for desktop is correct when I download it. Can you clarify exactly what credentials you are downloading in step 1? Maybe you can share the schema so I can identify what kind of credential they are?

**Comment by break-through** [comment]
Thanks for your reply! Here's the schema of the credentials.json file at the moment I had this issue:
{"WCc":{"client_id":"value","project_id":"value","Anc":"value","hVc":"value","znc":"value","s2a":"value","oNc":["value"]}}.

Those look like obfuscated keys. I'm going to try with what happens if I re-download credentails.json now, but wanted to reply with the requested info.
