### ISSUE TITLE
redirect_uri issue

### ISSUE THREAD

**Issue by pvssvikas** [googleapis/google-auth-library-python-oauthlib#54]
https://github.com/googleapis/google-auth-library-python-oauthlib/blob/7ce2a728256c1522d66e62a3a47c8416bad6bc91/google_auth_oauthlib/flow.py#L427

Hello Team,

http://{}:{}/ <-- the extra slash is causing an issue, as project settings pages do not allow path to get configured for the redirect_uri; and python code is even ignoring the redirect_uri passed as an argument in InstalledAppFlow.from_client_secrets_file

I could use the library by removing extra slash. I wish this gets corrected as part of the library itself.

Thanks,
-Vikas.

**Comment by busunkim96** [comment]
Hi @pvssvikas 

What sort of project settings pages are of you having issues with?

**Comment by busunkim96** [comment]
Closing as there has been no response. Please open a new issue if you are experiencing this issue.
