### ISSUE TITLE
run_local_server not works on heroku

### ISSUE THREAD

**Issue by Zhipeng-Chang** [googleapis/google-auth-library-python-oauthlib#55]
Hi, I have a project running on heroku, I'm trying to authenticate with Google API, but It doesn't open the new window, it works fine on my localhost. Does anyone know how to fix this?
Thanks

                flow = InstalledAppFlow.from_client_config(credentials, SCOPES)
                creds = flow.run_local_server(port=0)

**Comment by eics** [comment]
I have the same issue... did you manage to solve it?

**Comment by Thutmose3** [comment]
@jackson-zhipeng-chang Did you found a solution to this by any chance?
