### ISSUE TITLE
Install google_auth_oauthlib Python 3 on Mac

### ISSUE THREAD

**Issue by eabanoz** [googleapis/google-auth-library-python-oauthlib#68]
Hi,
I have tried to install google_auth_oauthlib into Python 3 with using pip and repository options. 

1) I get this error message for repository option:
Execute comment: pip install --index-url https://github.com/googleapis/google-auth-library-python-oauthlib/ google_auth_oauthlib
Error Occurred: ERROR: Could not find a version that satisfies the requirement google_auth_oauthlib (from versions: none)
Command output: Looking in indexes: https://github.com/googleapis/google-auth-library-python-oauthlib/

ERROR: Could not find a version that satisfies the requirement google_auth_oauthlib (from versions: none)
ERROR: No matching distribution found for google_auth_oauthlib

2) I didn't get error message for pip instal. But I couldn't see it in Python script when I use import command.
Terminal output:
Eness-MacBook-Pro:~ ea$ pip install google_auth_oauthlib
Requirement already satisfied: google_auth_oauthlib in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (0.4.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from google_auth_oauthlib) (1.3.0)
Requirement already satisfied: google-auth in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from google_auth_oauthlib) (1.9.0)
Requirement already satisfied: oauthlib>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google_auth_oauthlib) (3.1.0)
Requirement already satisfied: requests>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests-oauthlib>=0.7.0->google_auth_oauthlib) (2.22.0)
Requirement already satisfied: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from google-auth->google_auth_oauthlib) (1.13.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from google-auth->google_auth_oauthlib) (0.2.7)
Requirement already satisfied: cachetools<3.2,>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from google-auth->google_auth_oauthlib) (3.1.1)
Requirement already satisfied: rsa<4.1,>=3.1.4 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from google-auth->google_auth_oauthlib) (4.0)
Requirement already satisfied: setuptools>=40.3.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from google-auth->google_auth_oauthlib) (42.0.2)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib) (2019.11.28)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib) (1.25.7)
Requirement already satisfied: idna<2.9,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google_auth_oauthlib) (3.0.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from pyasn1-modules>=0.2.1->google-auth->google_auth_oauthlib) (0.4.8)

**Comment by busunkim96** [comment]
It looks like the package name is misspelled. The command below works for me.
```
pip install google-auth-oauthlib
```
