### ISSUE TITLE
Trailing Slash Breaks redirect_uri for localhost

### ISSUE THREAD

**Issue by paulmolloy** [googleapis/google-auth-library-python-oauthlib#80]
The concatenation of a slash on the end of the redirect_uri means that the redirect no longer matches what the server side expects for redirect_uri. 

Example:
redirect_uris= ['http://localhost:8080'] 
from client_config.json downloaded from https://console.cloud.google.com/apis/credentials

After flow adds the slash. 
The oauth url opened in the browser has:
"...&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&..."
the extra slash. 
If I remove the %2F slash from the URL it works. 

I guess this may be more a problem on the server side as it should probably still accept the URL with the slash.
Over on https://console.cloud.google.com/apis/credentials it doesn't allow adding a trailing slash anyway.
It's on line 456 of flow.py.

Error page from the extra slash URL:
"
Fehler bei der Autorisierung
Fehler 400: redirect_uri_mismatch
The redirect URI in the request, http://localhost:8080/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/53469...
"

**Comment by arithmetic1728** [comment]
@paulmolloy  You can set up multiple `redirect_uri` in the console, so once you add `http://localhost:8080/` I believe the code should work.

To add the additional `redirect_uri`, you can go to the https://console.cloud.google.com/apis/credentials page, edit the credentials under `OAuth 2.0 Client IDs`, then at the bottom of the new screen, there is a section called `Authorized redirect URIs`, then click `ADD URI` and add `http://localhost:8080/`.
