### ISSUE TITLE
Allow storing previously authenticated credentials to speed up flow.

### ISSUE THREAD

**Issue by HFulcher** [googleapis/google-auth-library-python-oauthlib#82]
Similar to functionality found in [oauth2client](https://github.com/googleapis/oauth2client/blob/master/oauth2client/tools.py#L142), it would be nice to have a way to automatically store credentials verified through a Flow. This could be used to easily check in future if a user needs to run through the process again. Below usage example from [here.](https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/installed-py)

```python
storage = file.Storage('analyticsreporting.dat')
credentials = storage.get()
if credentials is None or credentials.invalid:
    credentials = tools.run_flow(flow, storage, flags)
http = credentials.authorize(http=httplib2.Http())

```

**Comment by busunkim96** [comment]
Hi @HFulcher,

At the moment I think we are unlikely to implement credential storage in this library. `googe-auth` does have utility functions to convert between JSON and credentials objects. See https://googleapis.dev/python/google-auth/latest/reference/google.oauth2.credentials.html?highlight=to_json#google.oauth2.credentials.Credentials.to_json

**Comment by HFulcher** [comment]
Hi @busunkim96,

Thanks for the info. Would you be against me forking and putting an implementation together for a PR or would you rather it not be attemped?

**Comment by busunkim96** [comment]
@HFulcher The latter (at least at the moment). We're trying to keep the functionality of the auth libraries relatively consistent across the languages we support. 

That said, we'll keep this in mind as we look at new features to add. Thank you for filing an issue! 😄

**Comment by HFulcher** [comment]
@busunkim96 Understandable! I look forward to seeing what new features come in the future! 😊
