### ISSUE TITLE
unable to use --noauth_local_webserver for my script

### ISSUE THREAD

**Issue by marek141017** [googleapis/google-auth-library-python-oauthlib#83]
Hello 

I used to use --noauth_local_webserver to authorize my client

With new module it doesn't work
It always gives me a URL, but it won't work because redirect leads to localhost

**Comment by busunkim96** [comment]
@marek141017 Could you show us the code you're using?

**Comment by marek141017** [comment]
--noauth_local_webserver has nothing to do with code

It was used by oauth2client to allow enter the key from auth process instead of redirect to local server

It is not supported in google.auth

**Comment by tswast** [comment]
Are you referring to this method? https://google-auth-oauthlib.readthedocs.io/en/latest/reference/google_auth_oauthlib.html#google_auth_oauthlib.get_user_credentials

That always uses "console" based input rather than the redirect to local web server.

**Comment by westarle** [comment]
Closing due to age.  Please reopen if you are still experiencing this issue.
